spring:
  application:
    name: EasyLLMMain
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
logging:
  file:
    name: micro.log
tongyi:
  api-key: sk-40a4dab15f134fa0b2c5a4c7a7a44a1b
  model-name: qwen-turbo
