spring:
  datasource: #本地
    name: micro  #数据库名
    url: jdbc:mysql://localhost:3306/easy_llm?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root  #用户名
    password: mortmort08  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: mortmort08
    database: 10
    timeout: 5000
mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#数据库链接驱动
